image: java:8

before_script:
    - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew -g /cache/.gradle clean assemble
  allow_failure: false
  tags:
    - gradle

test:
  stage: test
  script:
    - ./gradlew -g /cache/.gradle check
    - ./gradlew -g /cache/.gradle pythonTest
  tags:
    - gradle